import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Loader2, ShieldCheck, AlertTriangle, Download, FileText, CheckCircle2, History } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { LineChart, Line, ResponsiveContainer } from "recharts";

export default function AuditPage() {
  const [selectedRepoId, setSelectedRepoId] = useState("");
  const [branch, setBranch] = useState("");
  const [currentAuditId, setCurrentAuditId] = useState<string | null>(null);
  const { toast } = useToast();

  const { data: repositories, isLoading: isLoadingRepos } = useQuery<any[]>({
    queryKey: ["/api/repositories"],
  });

  const selectedRepo = repositories?.find((r) => r.id === selectedRepoId);
  const repositoryUrl = selectedRepo ? `https://github.com/${selectedRepo.fullName}` : "";

  const { data: branches, isLoading: isLoadingBranches } = useQuery<string[]>({
    queryKey: [`/api/repositories/${selectedRepoId}/branches`],
    enabled: !!selectedRepoId,
    staleTime: 5 * 60 * 1000,
  });

  const { data: auditHistory } = useQuery<any[]>({
    queryKey: ["/api/audits/history", repositoryUrl],
    enabled: !!repositoryUrl,
  });

  const startAuditMutation = useMutation({
    mutationFn: async (data: { repositoryUrl: string; branch: string; framework: string }) => {
      const res = await apiRequest("POST", "/api/audits", data);
      return res.json();
    },
    onSuccess: (data) => {
      setCurrentAuditId(data.id);
      toast({
        title: "Audit Started",
        description: "Your repository is being cloned and analyzed.",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Audit Failed",
        description: error.message,
        variant: "destructive"
      });
    }
  });

  const verifySignatureMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", `/api/audits/${currentAuditId}/verify`);
      return res.json();
    },
    onSuccess: (data) => {
      if (data.isValid) {
        toast({
          title: "Signature Verified",
          description: "The report hash and cryptographic signature are valid and generated by CodeGuard.",
        });
      } else {
        toast({
          title: "Signature Verification Failed",
          description: "The report signature is invalid. The report may have been tampered with.",
          variant: "destructive"
        });
      }
    },
    onError: (error: Error) => {
      toast({
        title: "Verification Error",
        description: error.message,
        variant: "destructive"
      });
    }
  });

  const { data: audit } = useQuery<any>({
    queryKey: ["/api/audits", currentAuditId],
    enabled: !!currentAuditId,
    refetchInterval: (query) => {
      // @ts-ignore
      const status = query?.state?.data?.status;
      return (status === "pending" || status === "running") ? 3000 : false;
    }
  });

  const { data: report } = useQuery<any[]>({
    queryKey: ["/api/audits", currentAuditId, "report"],
    enabled: !!currentAuditId && audit?.status === "complete",
  });

  // Generate a mock sparkline data trend for the visual effect
  const chartData = auditHistory?.map((h, i) => ({ value: Math.max(1, 15 - i * 3) })).reverse() || [];

  return (
    <div className="container mx-auto py-8 px-4 max-w-5xl">
      <div className="mb-8">
        <h1 className="text-3xl font-bold tracking-tight mb-2">Audit Mode (ASVS 5.0)</h1>
        <p className="text-muted-foreground">
          Run a full-repository compliance audit against the OWASP Application Security Verification Standard 5.0.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="md:col-span-1 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>New Audit</CardTitle>
              <CardDescription>Target repository details</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label>Repository</Label>
                <Select
                  value={selectedRepoId}
                  onValueChange={(val) => {
                    setSelectedRepoId(val);
                    setBranch("");
                  }}
                  disabled={startAuditMutation.isPending || isLoadingRepos || (audit && audit.status === 'running')}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select a repository" />
                  </SelectTrigger>
                  <SelectContent>
                    {repositories?.map((repo) => (
                      <SelectItem key={repo.id} value={repo.id}>
                        {repo.fullName}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Branch</Label>
                <Select
                  value={branch}
                  onValueChange={setBranch}
                  disabled={!selectedRepoId || isLoadingBranches || startAuditMutation.isPending || (audit && audit.status === 'running')}
                >
                  <SelectTrigger>
                    <SelectValue placeholder={isLoadingBranches ? "Loading branches..." : "Select a branch"} />
                  </SelectTrigger>
                  <SelectContent>
                    {branches?.map((b) => (
                      <SelectItem key={b} value={b}>
                        {b}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <Button 
                className="w-full" 
                onClick={() => startAuditMutation.mutate({ repositoryUrl, branch, framework: "asvs-5.0" })}
                disabled={startAuditMutation.isPending || !repositoryUrl || !branch || (audit && audit.status === 'running')}
              >
                {startAuditMutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ShieldCheck className="mr-2 h-4 w-4" />}
                Run Audit
              </Button>
            </CardContent>
          </Card>

          ) : (
            <div className="h-full flex items-center justify-center border-2 border-dashed rounded-lg p-12 text-muted-foreground text-center bg-muted/10">
              Select a repository and branch to start a new compliance audit.
            </div>
          )}
        </div>
      </div>

      {auditHistory && auditHistory.length > 0 && (
        <Card className="mt-8">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center text-lg">
              <History className="w-4 h-4 mr-2" />
              Audit History
            </CardTitle>
            <CardDescription>Trend for {selectedRepo?.name}</CardDescription>
          </CardHeader>
          <CardContent>
            {chartData.length > 1 && (
              <div className="h-24 w-full mb-6 opacity-70">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={chartData}>
                    <Line type="monotone" dataKey="value" stroke="#ef4444" strokeWidth={2} dot={false} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            )}
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Date</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Action</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {auditHistory.map(h => (
                  <TableRow key={h.id}>
                    <TableCell className="py-2 text-sm">{new Date(h.startedAt).toLocaleDateString()} {new Date(h.startedAt).toLocaleTimeString()}</TableCell>
                    <TableCell className="py-2">
                      <Badge variant={h.status === 'complete' ? 'default' : h.status === 'failed' ? 'destructive' : 'secondary'} className="text-[10px] px-2 py-0.5 h-5">
                        {h.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="py-2 text-right">
                       <Button variant="ghost" size="sm" className="h-8 text-xs px-3" onClick={() => setCurrentAuditId(h.id)}>
                         View Report
                       </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
